### ISSUE TITLE
Generated wav files are not format-compliant

### ISSUE THREAD

**Issue by jofemodo** [kmatheussen/jack_capture#37]
When capturing a wav file like this:

`$ jack_capture -f wav`

the resulting file is not format-compliant:

```
$ soxi jack_capture_04.wav
soxi WARN wav: wave header missing extended part of fmt chunk

Input File     : 'jack_capture_04.wav'
Channels       : 2
Sample Rate    : 44100
Precision      : 25-bit
Duration       : 00:00:07.88 = 347648 samples = 591.238 CDDA sectors
File Size      : 2.78M
Bit Rate       : 2.82M
Sample Encoding: 32-bit Floating Point PCM
```

This makes the generated wav files unreadable for some libraries (i.e python's mutagen) and programs (i.e. firefox).

**Comment by kmatheussen** [comment]
The files are generated by libsndfile. Seems like, according to sox developer, the warning is caused by unclear wav specification, and sox "should really probably" not give a warning, similar to libsndfile and nu774: https://sourceforge.net/p/sox/mailman/sox-users/thread/512DBB45.3050507%40web.de/

The reason you can't open the file in firefox is probably just caused by firefox not being able to open floating point wav files. Try to give "-b 16" as argument to jack_capture.

**Comment by jofemodo** [comment]
Thanks! It worked ;-)
